<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

	<head>
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<title>[Page Title]</title>
		<link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection" />
	   	<link rel="stylesheet" href="/css/print.css" type="text/css" media="print" /> 
		<!--[if IE]>
			<link rel="stylesheet" href="css/ie.css" type="text/css" media="screen, projection" />
		<![endif]-->
	   	<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen, projection" />
		<script language="JavaScript" type="text/javascript" src="/js/mootools.js"></script>
		<script type="text/javascript" src=""></script>
		<?php if(isset($this->map)) {
		  $this->map->printHeader();
		}?>
	</head>
	
	<body>
		<div class="container showgrid">
			<h1 class="fancy">Page Title</h1>
			<div class="span-8">
				<p>
				<?php if($this->user) { ?> 
                    <span id="logged-in">
                        Logged in as <?php  echo $this->escape($this->user->username); ?>. 
                        <a href="<?php echo $this->baseUrl ?>/auth/logout">Logout</a>
                    </span> 
                    <?php } ?>
                </p>
			</div>
			<div class="span-16 last">
				<p>Some More Text.</p>
			</div>
			<div class="span-24 last">
				<p><?php echo $this->layout()->content; ?></p>
			</div>
		</div>
	</body>
	
</html>